/* Perfis demonstrativos dos segmentos atendidos pela Ogritech. */
window.OGRITECH_BUSINESSES = {
    servicos: { name: "Negócio de demonstração", segment: "Serviços", icon: "◆", color: "#6de2f2", owner: "Marina Costa", employee: "Carlos", client: "João Silva", clientLabel: "Cliente", clientPlural: "Clientes", hero: "Seu próximo atendimento começa aqui.", revenue: 4850, ticket: 78, professionals: ["Carlos", "Rafael"], services: [["Atendimento inicial",45,"Atendimento personalizado para sua necessidade."],["Atendimento completo",75,"Serviço completo com acompanhamento profissional."],["Avaliação",35,"Avaliação inicial e orientação personalizada."],["Sessão especializada",120,"Atendimento especializado e personalizado."]] },
    barbearia: { name: "Japa na Barba", segment: "Barbearia", icon: "✂", color: "#6de2f2", owner: "Marina Costa", employee: "Carlos", client: "João Silva", clientLabel: "Cliente", clientPlural: "Clientes", hero: "Seu próximo visual começa aqui.", revenue: 4850, ticket: 78, professionals: ["Carlos", "Rafael"], services: [["Corte masculino",45,"Corte tradicional ou moderno."],["Corte + Barba",75,"Combo completo para renovar o visual."],["Barba",35,"Acabamento e alinhamento da barba."],["Platinado",120,"Transformação completa do visual."]] },
    salao: { name: "Studio Bella Forma", segment: "Salão de beleza", icon: "✦", color: "#d67ae4", owner: "Camila Rocha", employee: "Fernanda", client: "Mariana Alves", clientLabel: "Cliente", clientPlural: "Clientes", hero: "Realce sua beleza e reserve seu momento.", revenue: 21950, ticket: 153, professionals: ["Camila", "Fernanda", "Aline"], services: [["Corte feminino",120,"Corte personalizado para seu estilo."],["Escova",70,"Finalização com brilho e movimento."],["Coloração",240,"Cor e tratamento profissional."],["Hidratação",95,"Cuidado profundo para os fios."]] },
    manicure: { name: "Nail Art Boutique", segment: "Manicure e esmalteria", icon: "◇", color: "#ef8eb6", owner: "Bianca Souza", employee: "Lívia", client: "Ana Clara", clientLabel: "Cliente", clientPlural: "Clientes", hero: "Unhas impecáveis começam com seu horário reservado.", revenue: 11420, ticket: 92, professionals: ["Bianca", "Lívia", "Nayara"], services: [["Mão e pé",65,"Cuidado completo para mãos e pés."],["Alongamento em gel",160,"Alongamento resistente e natural."],["Manutenção de gel",95,"Renovação e acabamento do gel."],["Spa dos pés",75,"Relaxamento e hidratação profunda."]] },
    estetica: { name: "Lumina Estética", segment: "Clínica de estética", icon: "◉", color: "#78d7c5", owner: "Marina Lopes", employee: "Sofia", client: "Elaine Prado", clientLabel: "Paciente", clientPlural: "Pacientes", hero: "Seu cuidado e bem-estar começam aqui.", revenue: 28400, ticket: 326, professionals: ["Marina", "Sofia", "Carla"], services: [["Limpeza de pele",150,"Renovação e cuidado facial."],["Drenagem linfática",130,"Bem-estar e redução de inchaço."],["Microagulhamento",320,"Protocolo avançado para a pele."],["Massagem modeladora",140,"Cuidado corporal personalizado."]] },
    petshop: { name: "Pet & Cia Care", segment: "Pet shop", icon: "●", color: "#71b9ef", owner: "Paulo Vieira", employee: "Jéssica", client: "Marcos e Thor", clientLabel: "Tutor", clientPlural: "Tutores", hero: "O próximo cuidado do seu pet começa aqui.", revenue: 17680, ticket: 104, professionals: ["Paulo", "Jéssica", "Tiago"], services: [["Banho",65,"Higiene e cuidado para o pet."],["Banho e tosa",110,"Cuidado completo e personalizado."],["Tosa higiênica",55,"Conforto e higiene no dia a dia."],["Hidratação",45,"Pelagem macia e bem cuidada."]] },
    bronzeamento: { name: "Sol Dourado Studio", segment: "Bronzeamento", icon: "☀", color: "#f1aa4c", owner: "Patrícia Melo", employee: "Daiane", client: "Carolina Reis", clientLabel: "Cliente", clientPlural: "Clientes", hero: "Seu momento de brilho começa aqui.", revenue: 13650, ticket: 184, professionals: ["Patrícia", "Daiane"], services: [["Bronze natural",130,"Sessão personalizada ao ar livre."],["Bronze a jato",110,"Resultado uniforme e rápido."],["Pacote 3 sessões",330,"Evolução acompanhada em três sessões."],["Esfoliação corporal",85,"Preparação e renovação da pele."]] },
    personal: { name: "Evolve Personal", segment: "Personal training", icon: "◆", color: "#67d49b", owner: "Marcelo Torres", employee: "Isabela", client: "Ricardo Nunes", clientLabel: "Aluno", clientPlural: "Alunos", hero: "Seu próximo resultado começa com um treino.", revenue: 19400, ticket: 156, professionals: ["Marcelo", "Isabela", "Diego"], services: [["Treino individual",100,"Sessão focada nos seus objetivos."],["Treino em dupla",140,"Evolução compartilhada e motivadora."],["Avaliação física",150,"Diagnóstico e definição de metas."],["Consultoria online",220,"Acompanhamento onde você estiver."]] },
    musica: { name: "Harmonia Escola", segment: "Aulas de música", icon: "♫", color: "#829ef5", owner: "Eduardo Campos", employee: "Mônica", client: "Gabriel Souza", clientLabel: "Aluno", clientPlural: "Alunos", hero: "Sua evolução musical começa na próxima aula.", revenue: 16380, ticket: 105, professionals: ["Eduardo", "Mônica", "Felipe"], services: [["Aula de violão",90,"Prática e repertório personalizados."],["Aula de piano",110,"Técnica, leitura e expressão musical."],["Aula de canto",100,"Respiração, técnica e interpretação."],["Teoria musical",75,"Fundamentos para acelerar a evolução."]] },
    clinica: { name: "Clínica Vitta", segment: "Clínica de saúde", icon: "✚", color: "#59c8df", owner: "Laura Nunes", employee: "Paula", client: "Marcos Vieira", clientLabel: "Paciente", clientPlural: "Pacientes", hero: "Seu próximo cuidado começa com um horário reservado.", revenue: 42700, ticket: 230, professionals: ["Laura", "André", "Paula"], services: [["Consulta inicial",250,"Avaliação completa e plano de cuidado."],["Retorno",160,"Acompanhamento da sua evolução."],["Fisioterapia",120,"Sessão individual de reabilitação."],["Nutrição",200,"Avaliação e orientação nutricional."]] },
    mentoria: { name: "Impulso Mentoria", segment: "Coaching e mentoria", icon: "▲", color: "#c28cf0", owner: "Helena Duarte", employee: "Rodrigo", client: "Daniel Martins", clientLabel: "Mentorado", clientPlural: "Mentorados", hero: "Seu próximo avanço começa com uma conversa estratégica.", revenue: 24600, ticket: 362, professionals: ["Helena", "Rodrigo"], services: [["Sessão estratégica",350,"Clareza e plano para o próximo passo."],["Mentoria individual",600,"Acompanhamento personalizado."],["Programa de carreira",1200,"Jornada completa de desenvolvimento."],["Workshop em grupo",180,"Aprendizado colaborativo e prático."]] }
};

window.getOgritechBusiness = function () {
    const key = sessionStorage.getItem("japaDemoSegment") || "servicos";
    return { key, ...(window.OGRITECH_BUSINESSES[key] || window.OGRITECH_BUSINESSES.servicos) };
};

window.applyOgritechBusinessTheme = function (business) {
    const accent = business?.color || "#d4af37";
    const hex = accent.replace("#", "");
    const rgb = hex.length === 6
        ? [0, 2, 4].map((index) => parseInt(hex.slice(index, index + 2), 16)).join(",")
        : "212,175,55";
    document.documentElement.style.setProperty("--gold", accent);
    document.documentElement.style.setProperty("--gold-light", accent);
    document.documentElement.style.setProperty("--accent-rgb", rgb);
};
