const params = new URLSearchParams(location.search);
const slug = (params.get("empresa") || "").trim();
const AUTH_REQUIRED = params.get("auth") === "required";
const DRAFT_TTL_MS = 15 * 60 * 1000;
const PREFERENCE_TTL_MS = 30 * 24 * 60 * 60 * 1000;
const storageScope = `${window.OGRITECH_ENV || "production"}:${slug}`;
const draftKey = `ogritechBookingDraft:${storageScope}`;
const preferenceKey = `ogritechBookingPreferences:${storageScope}`;
const state = { page: null, service: null, professional: null, date: "", time: "", session: null, booking: null };
const $ = (id) => document.getElementById(id);
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function escapeHtml(value) { const div = document.createElement("div"); div.textContent = String(value ?? ""); return div.innerHTML; }
function environmentHref(path) { const url = new URL(path, location.href); if (window.OGRITECH_ENV !== "production") url.searchParams.set("env", window.OGRITECH_ENV); return url; }
function setError(message) { $("loadingState").classList.add("hidden"); $("bookingForm").classList.add("hidden"); $("errorState").classList.remove("hidden"); $("errorMessage").textContent = message; }
function formatDate(value) { return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" }); }
function statusLabel(status) { return ({ requested: "Aguardando confirmação", confirmed: "Confirmado", completed: "Concluído", cancelled: "Cancelado", no_show: "Não compareceu" })[status] || status; }
function enable(id, enabled = true) { const section = $(id); section.classList.toggle("disabled-step", !enabled); section.inert = !enabled; }
function readExpiringStorage(storage, key) { try { const value = JSON.parse(storage.getItem(key) || "null"); if (!value || value.expiresAt <= Date.now()) { storage.removeItem(key); return null; } return value; } catch { return null; } }
function saveDraft() { try { sessionStorage.setItem(draftKey, JSON.stringify({ serviceId: state.service?.id || null, professionalId: state.professional?.id || null, date: state.date, time: state.time, expiresAt: Date.now() + DRAFT_TTL_MS })); } catch {} }
function savePreferences() { try { localStorage.setItem(preferenceKey, JSON.stringify({ serviceId: state.service?.id || null, professionalId: state.professional?.id || null, expiresAt: Date.now() + PREFERENCE_TTL_MS })); } catch {} }
function clearDraft() { try { sessionStorage.removeItem(draftKey); } catch {} }
function renderSummary() { if (!state.service || !state.professional || !state.date || !state.time) return; $("bookingSummary").innerHTML = `<strong>${escapeHtml(state.service.name)}</strong> com ${escapeHtml(state.professional.name)}<br>${escapeHtml(formatDate(state.date))}, às ${escapeHtml(state.time)} · ${money.format(Number(state.service.price))}`; }
function renderProfessionals() { const available = state.page.professionals.filter((professional) => (professional.service_ids || []).includes(state.service.id)); $("professionalChoices").innerHTML = available.map((professional) => `<label class="choice-card"><input type="radio" name="professional" value="${professional.id}"><strong>${escapeHtml(professional.name)}</strong><small>${escapeHtml(professional.specialty || "Atendimento geral")}</small></label>`).join("") || '<p class="hint">Nenhum profissional disponível para este serviço.</p>'; enable("professionalStep", available.length > 0); }
async function loadSlots() { if (!state.service || !state.professional || !state.date) { $("slotChoices").innerHTML = '<p class="hint">Selecione serviço, profissional e data.</p>'; return []; } state.time = ""; $("bookingTime").value = ""; enable("contactStep", false); $("slotChoices").innerHTML = '<p class="hint">Buscando a agenda do profissional…</p>'; saveDraft(); const args = { target_slug: slug, target_service_id: state.service.id, target_employee_id: state.professional.id, target_date: state.date }; let { data, error } = await supabaseClient.rpc("public_visual_schedule", args); if (error) { const fallback = await supabaseClient.rpc("public_available_slots", args); data = (fallback.data || []).map((row) => ({ slot_time: row.slot_time, is_available: true })); error = fallback.error; } if (error) { $("slotChoices").innerHTML = '<p class="hint">Não foi possível consultar os horários.</p>'; return []; } const schedule = (data || []).map((row) => ({ time: String(row.slot_time).slice(0, 5), available: row.is_available !== false })); const slots = schedule.filter((row) => row.available).map((row) => row.time); $("slotChoices").innerHTML = schedule.length ? schedule.map((row) => `<button type="button" class="slot-button${row.available ? "" : " unavailable"}" data-time="${row.time}" ${row.available ? "" : 'disabled aria-label="Horário indisponível" title="O profissional não está disponível neste horário"'}>${row.time}</button>`).join("") : '<p class="hint">Este profissional não atende nesta data. Pode ser folga, férias ou ausência.</p>'; return slots; }
function updateIdentity(session) { state.session = session || null; const panel = $("identityPanel"), status = $("identityStatus"); panel.classList.toggle("is-authenticated", Boolean(session)); $("myAppointments").classList.toggle("hidden", !session); if (!session) { status.textContent = AUTH_REQUIRED ? "Identifique-se para confirmar o horário." : "Você também pode continuar preenchendo os dados abaixo."; return; } const user = session.user; const name = user.user_metadata?.full_name || user.user_metadata?.name || "Cliente identificado"; status.textContent = `Identidade confirmada: ${name}.`; if (!$("clientName").value) $("clientName").value = name; if (!$("clientEmail").value && user.email) $("clientEmail").value = user.email; if (!$("clientPhone").value && user.phone) $("clientPhone").value = user.phone; if (state.page) loadMyAppointments(); }
function normalizeBrazilPhone(value) { const digits = String(value || "").replace(/\D/g, ""); if (digits.startsWith("55") && digits.length >= 12) return `+${digits}`; return digits.length >= 10 ? `+55${digits}` : ""; }
async function restoreSelection() { const draft = readExpiringStorage(sessionStorage, draftKey); const preferences = readExpiringStorage(localStorage, preferenceKey); const source = draft || preferences; if (!source) return; const service = state.page.services.find((item) => item.id === source.serviceId); if (!service) return; state.service = service; const serviceInput = document.querySelector(`input[name="service"][value="${CSS.escape(service.id)}"]`); if (serviceInput) serviceInput.checked = true; renderProfessionals(); const professional = state.page.professionals.find((item) => item.id === source.professionalId && (item.service_ids || []).includes(service.id)); if (!professional) return; state.professional = professional; const professionalInput = document.querySelector(`input[name="professional"][value="${CSS.escape(professional.id)}"]`); if (professionalInput) professionalInput.checked = true; enable("dateStep"); if (!draft?.date) return; state.date = draft.date; $("bookingDate").value = draft.date; const slots = await loadSlots(); if (draft.time && slots.includes(draft.time)) { state.time = draft.time; $("bookingTime").value = draft.time; $("slotChoices").querySelector(`[data-time="${CSS.escape(draft.time)}"]`)?.classList.add("active"); enable("contactStep"); renderSummary(); } }
function managementUrl(booking) { const url = environmentHref(`./?empresa=${encodeURIComponent(slug)}`); url.hash = new URLSearchParams({ reserva: booking.reference, token: booking.token }).toString(); return url; }
function showSuccess(booking) { state.booking = booking; clearDraft(); savePreferences(); $("bookingForm").classList.add("hidden"); $("successState").classList.remove("hidden"); $("successDetail").innerHTML = `<strong>${escapeHtml(booking.service)}</strong><br>${escapeHtml(formatDate(booking.date))}, às ${escapeHtml(String(booking.time).slice(0, 5))}<br>Profissional: ${escapeHtml(booking.professional)}<br>Status: ${escapeHtml(statusLabel(booking.status))}`; $("successReference").textContent = booking.reference; $("manageBookingLink").href = managementUrl(booking).href; $("successMessage").textContent = ""; history.replaceState(null, "", managementUrl(booking).href); }
async function loadManagement(reference, token) { $("loadingState").classList.add("hidden"); $("bookingForm").classList.add("hidden"); $("manageState").classList.remove("hidden"); const { data, error } = await supabaseClient.rpc("public_get_appointment", { target_reference: reference, target_token: token }); if (error || !data) { $("businessName").textContent = "Consultar agendamento"; $("manageTitle").textContent = "Agendamento não encontrado"; $("manageMessage").textContent = "Não foi possível abrir este agendamento."; return; } $("businessName").textContent = data.business; $("businessIntro").textContent = "Consulte os detalhes e acompanhe sua reserva."; document.title = `Minha reserva | Ogritech`; $("manageTitle").textContent = data.business; $("manageDetail").innerHTML = `<strong>${escapeHtml(data.service)}</strong><br>${escapeHtml(formatDate(data.date))}, às ${escapeHtml(String(data.time).slice(0, 5))}<br>Profissional: ${escapeHtml(data.professional)}<br>Status: <strong>${escapeHtml(statusLabel(data.status))}</strong>`; $("cancelBookingButton").classList.toggle("hidden", !data.can_cancel); $("cancelBookingButton").onclick = async () => { if (!confirm("Deseja realmente cancelar este agendamento?")) return; const button = $("cancelBookingButton"); button.disabled = true; const { data: cancelled, error: cancelError } = await supabaseClient.rpc("public_cancel_appointment", { target_reference: reference, target_token: token }); if (cancelError || !cancelled) { $("manageMessage").textContent = "Não foi possível cancelar. Atualize a página e tente novamente."; button.disabled = false; return; } button.classList.add("hidden"); $("manageMessage").textContent = "Agendamento cancelado com sucesso."; $("manageMessage").style.color = "var(--ok)"; $("manageDetail").innerHTML = $("manageDetail").innerHTML.replace(/Status: <strong>.*<\/strong>/, "Status: <strong>Cancelado</strong>"); }; }
async function loadMyAppointments() { const list = $("myAppointmentsList"); list.innerHTML = '<p class="hint">Consultando seus agendamentos…</p>'; const { data, error } = await supabaseClient.rpc("client_list_my_appointments", { target_slug: slug }); if (error) { list.innerHTML = '<p class="hint">Seus agendamentos estarão disponíveis após a atualização do serviço.</p>'; return; } list.innerHTML = data?.length ? `<div class="appointment-list">${data.map((item) => `<article class="appointment-list-item"><strong>${escapeHtml(item.service)}</strong><p>${escapeHtml(formatDate(item.date))}, às ${escapeHtml(String(item.time).slice(0, 5))} · ${escapeHtml(item.professional)}</p><span>${escapeHtml(statusLabel(item.status))}</span>${item.can_cancel ? `<button class="danger-button" type="button" data-cancel-id="${escapeHtml(item.id)}">Cancelar</button>` : ""}</article>`).join("")}</div>` : '<p class="hint">Nenhum agendamento vinculado a esta conta.</p>'; }
async function initialize() { const hash = new URLSearchParams(location.hash.slice(1)); const reference = hash.get("reserva"), token = hash.get("token"); $("backToBooking").href = environmentHref(`./?empresa=${encodeURIComponent(slug)}`).href; if (reference && token) return loadManagement(reference, token); if (!slug) return setError("O endereço da empresa não foi informado."); const [{ data, error }, authResult] = await Promise.all([supabaseClient.rpc("public_booking_page", { target_slug: slug }), supabaseClient.auth.getSession()]); if (error || !data) return setError("Confira o link recebido ou tente novamente mais tarde."); state.page = data; updateIdentity(authResult.data?.session); document.title = `Agendar com ${data.business.name} | Ogritech`; $("businessName").textContent = data.business.name; $("businessIntro").textContent = "Escolha o serviço, o profissional e o melhor horário para você."; $("serviceChoices").innerHTML = data.services.map((service) => `<label class="choice-card"><input type="radio" name="service" value="${service.id}"><strong>${escapeHtml(service.name)}</strong><small>${escapeHtml(service.description || `${service.duration_minutes} minutos`)}</small><b>${money.format(Number(service.price))}</b></label>`).join(""); const today = new Date(), max = new Date(); max.setDate(max.getDate() + 60); $("bookingDate").min = today.toISOString().slice(0, 10); $("bookingDate").max = max.toISOString().slice(0, 10); $("loadingState").classList.add("hidden"); $("bookingForm").classList.remove("hidden"); await restoreSelection(); }

$("serviceChoices").addEventListener("change", (event) => { state.service = state.page.services.find((item) => item.id === event.target.value); state.professional = null; state.date = ""; state.time = ""; $("bookingDate").value = ""; renderProfessionals(); enable("dateStep", false); enable("contactStep", false); saveDraft(); });
$("professionalChoices").addEventListener("change", (event) => { state.professional = state.page.professionals.find((item) => item.id === event.target.value); state.date = ""; state.time = ""; $("bookingDate").value = ""; enable("dateStep"); enable("contactStep", false); saveDraft(); });
$("bookingDate").addEventListener("change", () => { state.date = $("bookingDate").value; if (state.date) loadSlots(); });
$("bookingTime").addEventListener("change", () => { const typed = $("bookingTime").value; const available = [...$("slotChoices").querySelectorAll(".slot-button:not(.unavailable)")].some((button) => button.dataset.time === typed); if (!available) { state.time = ""; enable("contactStep", false); $("timeHelp").textContent = "Esse horário está indisponível. Escolha um horário verde."; return; } $("slotChoices").querySelectorAll(".slot-button").forEach((item) => item.classList.toggle("active", item.dataset.time === typed)); state.time = typed; $("timeHelp").textContent = "Horário livre selecionado."; enable("contactStep"); renderSummary(); saveDraft(); });
$("slotChoices").addEventListener("click", (event) => { const button = event.target.closest("[data-time]"); if (!button || button.disabled) return; $("slotChoices").querySelectorAll(".slot-button").forEach((item) => item.classList.remove("active")); button.classList.add("active"); state.time = button.dataset.time; $("bookingTime").value = state.time; $("timeHelp").textContent = "Horário livre selecionado."; enable("contactStep"); renderSummary(); saveDraft(); $("contactStep").scrollIntoView({ behavior: "smooth", block: "start" }); });
$("sendPhoneOtpButton").addEventListener("click", async () => { const phone = normalizeBrazilPhone($("clientPhone").value); if (!phone) { $("identityStatus").textContent = "Informe um celular válido com DDD."; $("clientPhone").focus(); return; } $("sendPhoneOtpButton").disabled = true; $("identityStatus").textContent = "Enviando código…"; const { error } = await supabaseClient.auth.signInWithOtp({ phone }); $("sendPhoneOtpButton").disabled = false; if (error) { $("identityStatus").textContent = AUTH_REQUIRED ? "O acesso por celular está indisponível. Tente novamente mais tarde." : "O acesso por celular ainda não está disponível. Você pode continuar com seus dados."; return; } $("otpVerification").classList.remove("hidden"); $("identityStatus").textContent = "Digite o código enviado ao seu celular."; $("phoneOtp").focus(); });
$("verifyPhoneOtpButton").addEventListener("click", async () => { const phone = normalizeBrazilPhone($("clientPhone").value), token = $("phoneOtp").value.trim(); if (!phone || !/^\d{6}$/.test(token)) { $("identityStatus").textContent = "Informe o código de seis números."; return; } const { data, error } = await supabaseClient.auth.verifyOtp({ phone, token, type: "sms" }); if (error || !data.session) { $("identityStatus").textContent = "Código inválido ou expirado."; return; } await supabaseClient.rpc("client_claim_phone_appointments", { target_slug: slug }); updateIdentity(data.session); $("identityStatus").textContent = "Celular confirmado. Veja abaixo seus horários reservados ou faça uma nova reserva."; });
$("bookingForm").addEventListener("submit", async (event) => { event.preventDefault(); const message = $("formMessage"), button = $("submitBooking"); if (!state.time) { message.textContent = "Escolha um horário disponível."; return; } if (AUTH_REQUIRED && !state.session) { message.textContent = "Confirme seu celular para concluir."; $("identityPanel").scrollIntoView({ behavior: "smooth" }); return; } const email = $("clientEmail").value.trim() || state.session?.user?.email || ""; if (!email) { message.textContent = "Enquanto a confirmação por celular é finalizada, informe também seu e-mail."; $("clientEmail").focus(); return; } button.disabled = true; button.textContent = "Enviando solicitação…"; message.textContent = ""; const { data, error } = await supabaseClient.rpc("public_create_appointment", { target_slug: slug, target_service_id: state.service.id, target_employee_id: state.professional.id, target_date: state.date, target_time: state.time, supplied_name: $("clientName").value.trim(), supplied_email: email, supplied_phone: $("clientPhone").value.trim(), accepted_privacy: $("privacyConsent").checked, website: $("clientWebsite").value }); button.disabled = false; button.textContent = "Solicitar agendamento"; if (error) { message.textContent = error.code === "23505" ? "Este horário acabou de ser ocupado. Escolha outro horário." : (error.message || "Não foi possível concluir o agendamento."); if (error.code === "23505") loadSlots(); return; } await supabaseClient.rpc("public_record_appointment_consents", { target_reference: data.reference, target_token: data.token, accepted_whatsapp_operational: $("whatsappConsent").checked, accepted_marketing: $("marketingConsent").checked }); showSuccess(data); if (state.session) loadMyAppointments(); });
$("myAppointmentsList").addEventListener("click", async (event) => { const button = event.target.closest("[data-cancel-id]"); if (!button || !confirm("Deseja realmente cancelar este agendamento?")) return; button.disabled = true; const { data, error } = await supabaseClient.rpc("client_cancel_my_appointment", { target_appointment_id: button.dataset.cancelId }); if (error || !data) { $("myAppointmentsMessage").textContent = "Não foi possível cancelar. Atualize seus agendamentos e tente novamente."; button.disabled = false; return; } $("myAppointmentsMessage").textContent = "Agendamento cancelado com sucesso."; loadMyAppointments(); });
$("cancelSuccessBookingButton").addEventListener("click", async () => { if (!state.booking || !confirm("Deseja realmente cancelar este agendamento?")) return; const button = $("cancelSuccessBookingButton"); button.disabled = true; const { data, error } = await supabaseClient.rpc("public_cancel_appointment", { target_reference: state.booking.reference, target_token: state.booking.token }); if (error || !data) { $("successMessage").textContent = "Não foi possível cancelar. Use o link da reserva para consultar e tentar novamente."; button.disabled = false; return; } $("successMessage").textContent = "Agendamento cancelado com sucesso."; button.classList.add("hidden"); $("successDetail").innerHTML = $("successDetail").innerHTML.replace(/Status: .*/, "Status: Cancelado"); });
$("newBookingButton").addEventListener("click", () => { location.href = environmentHref(`./?empresa=${encodeURIComponent(slug)}`).href; });
$("backButton").addEventListener("click", () => { if (history.length > 1) history.back(); else location.href = environmentHref("../").href; });
supabaseClient.auth.onAuthStateChange((_event, session) => updateIdentity(session));
initialize().catch(() => setError("Não foi possível carregar esta agenda agora."));