(() => {
  const form = document.querySelector("#lead-form"), steps = [...document.querySelectorAll(".step")], progress = [...document.querySelectorAll(".progress span")];
  const prev = document.querySelector("#prev"), next = document.querySelector("#next"), send = document.querySelector("#send"), note = document.querySelector("#note"), alertBox = document.querySelector("#alert"), current = document.querySelector("#current"), tool = document.querySelector("#tool"), adaptive = document.querySelector("#adaptive");
  let active = 0;
  document.querySelector(".honeypot")?.classList.add("hidden");
  form.whatsapp.addEventListener("input", e => { e.target.value = e.target.value.replace(/\D/g, "").slice(0, 11).replace(/^(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2"); });
  current.addEventListener("change", () => tool.classList.toggle("hidden", current.value === "Não"));
  const questions = { "Ogritech Agenda": ["Atendimentos por mês", "Quantos profissionais usarão a agenda?"], "Ogritech Páginas": ["Principal objetivo da página", "Já possui domínio?"], "Ogritech Orçamentos": ["Orçamentos por mês", "Como envia os orçamentos hoje?"], "Ogritech Cardápio": ["Quantidade aproximada de produtos", "Onde recebe pedidos hoje?"] };
  form.querySelectorAll("[name=interesse]").forEach(input => input.addEventListener("change", () => { adaptive.innerHTML = [...form.querySelectorAll("[name=interesse]:checked")].map(item => { const q = questions[item.value], key = item.value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\W/g, "_").toLowerCase(); return `<article><h3>${item.value}</h3><div class="grid"><label><span>${q[0]}</span><input name="${key}_1" maxlength="200"></label><label><span>${q[1]}</span><input name="${key}_2" maxlength="200"></label></div></article>`; }).join(""); }));
  form.querySelectorAll("[name=objetivo]").forEach(input => input.addEventListener("change", () => { if (form.querySelectorAll("[name=objetivo]:checked").length > 3) input.checked = false; }));
  function show(step) { active = step; steps.forEach((item, i) => item.classList.toggle("active", i === step)); progress.forEach((item, i) => item.classList.toggle("active", i <= step)); prev.classList.toggle("hidden", step === 0); next.classList.toggle("hidden", step === 2); send.classList.toggle("hidden", step !== 2); note.classList.toggle("hidden", step !== 2); note.textContent = window.OGRITECH_ENV === "staging" ? "Ambiente de teste: o contato será registrado na fila de staging." : "Ao enviar, seu aplicativo de e-mail será aberto com as respostas prontas para contato@ogritech.com.br."; alertBox.textContent = ""; document.querySelector(".form-shell").scrollIntoView({ behavior: "smooth", block: "start" }); }
  function valid() { let invalid = null; steps[active].querySelectorAll("[required]").forEach(field => { const ok = field.type === "checkbox" ? field.checked : field.checkValidity(); field.setAttribute("aria-invalid", String(!ok)); if (!ok && !invalid) invalid = field; }); if (!invalid) return true; alertBox.textContent = invalid.type === "checkbox" ? "Confirme o consentimento para continuar." : "Preencha os campos obrigatórios antes de continuar."; invalid.focus(); return false; }
  const selected = (data, name) => data.getAll(name).filter(Boolean);
  function adaptiveAnswers(data) { const answers = {}; for (const [key, value] of data) if (/_(1|2)$/.test(key) && value) answers[key] = String(value).slice(0, 200); return answers; }
  async function submitToStaging(data) {
    const { error } = await supabaseClient.rpc("public_submit_platform_contact", { supplied_name: data.get("nome"), supplied_company: data.get("empresa") || "", supplied_phone: data.get("whatsapp"), supplied_email: data.get("email"), supplied_location: data.get("localizacao") || "", supplied_preference: data.get("preferencia") || "WhatsApp", supplied_business_type: data.get("tipo_negocio") || "", supplied_employee_range: data.get("funcionarios") || "", supplied_customer_source: data.get("origem_clientes") || "", supplied_current_solution: data.get("solucao_atual") || "", supplied_current_tool: data.get("ferramenta_atual") || "", supplied_interests: selected(data, "interesse"), supplied_goals: selected(data, "objetivo"), supplied_timeline: data.get("prazo") || "", supplied_investment: data.get("investimento") || "", supplied_challenge: data.get("desafio") || "", supplied_adaptive_answers: adaptiveAnswers(data), accepted_privacy: data.get("consentimento") === "on", website: data.get("website") || "" });
    if (error) throw error; form.reset(); adaptive.innerHTML = ""; show(0); alertBox.classList.add("success"); alertBox.textContent = "Contato de teste registrado com sucesso na fila de staging.";
  }
  function openEmail(data) { const values = new Map(); for (const [key, value] of data) { if (!value || key === "consentimento" || key === "website") continue; const label = key.replace(/_/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()); values.set(label, [...(values.get(label) || []), value]); } const lines = []; values.forEach((value, key) => lines.push(`${key}: ${value.join(", ")}`)); location.href = `mailto:contato@ogritech.com.br?subject=${encodeURIComponent(`Novo interesse Ogritech — ${data.get("nome")}`)}&body=${encodeURIComponent(`Olá, Ogritech!\n\nGostaria de receber um contato.\n\n${lines.join("\n")}\n\nEnviado pelo formulário em ogritech.com.br.`)}`; }
  next.addEventListener("click", () => { if (valid()) show(active + 1); }); prev.addEventListener("click", () => show(active - 1));
  form.addEventListener("submit", async e => { e.preventDefault(); if (!valid()) return; const data = new FormData(form); if (window.OGRITECH_ENV !== "staging") return openEmail(data); send.disabled = true; alertBox.classList.remove("success"); alertBox.textContent = "Registrando contato de teste..."; try { await submitToStaging(data); } catch (error) { alertBox.textContent = error?.message || "Não foi possível registrar o contato. Tente novamente."; } finally { send.disabled = false; } });
})();
