(() => {
  const TERMS_VERSION="2.0-2026-09-06", prices={monthly:{months:1,discount:0,total:9700,label:"mensal"},quarterly:{months:3,discount:3,total:28227,label:"trimestral"},semiannual:{months:6,discount:5,total:55290,label:"semestral"},annual:{months:12,discount:10,total:104760,label:"anual"}};
  const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}), form=document.querySelector("#billingForm"), summary=document.querySelector("#summary"), recurring=document.querySelector("#recurringConsent"), recurringText=document.querySelector("#recurringText"), message=document.querySelector("#formMessage"), submit=document.querySelector("#submitButton");
  const config=()=>({url:window.OGRITECH_SUPABASE_URL,key:window.OGRITECH_SUPABASE_PUBLISHABLE_KEY});
  function update(){const cycle=prices[form.elements.cycle.value],card=form.elements.payment_method.value==="card"; summary.innerHTML=`<strong>${money.format(cycle.total/100)} por período ${cycle.label}</strong><br><small>${cycle.discount?`${cycle.discount}% de desconto sobre ${money.format(97*cycle.months)}.`:"Valor integral, sem desconto."} Após 14 dias gratuitos.</small>`; recurring.hidden=!card; form.elements.recurring_authorized.required=card; if(!card)form.elements.recurring_authorized.checked=false; recurringText.textContent=`Autorizo a cobrança recorrente de ${money.format(cycle.total/100)} a cada ${cycle.months===1?"mês":`${cycle.months} meses`}, depois dos 14 dias, até o cancelamento.`}
  function formatCnpj(v){return v.replace(/\D/g,"").slice(0,14).replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2")}
  form.elements.tax_document.addEventListener("input",e=>e.target.value=formatCnpj(e.target.value)); form.elements.phone.addEventListener("input",e=>e.target.value=e.target.value.replace(/\D/g,"").slice(0,11).replace(/^(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2")); form.addEventListener("change",update); update();
  async function call(body,token=""){const {url,key}=config();if(!url||!key)throw new Error("Ambiente de contratação indisponível.");const response=await fetch(`${url}/functions/v1/ogritech-billing`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json",...(token?{"x-management-token":token}:{})},body:JSON.stringify(body)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error?.message||({trial_already_used:"Este CNPJ já utilizou o teste gratuito.",terms_not_configured:"A contratação ainda não foi configurada para produção.",billing_not_configured:"A contratação está temporariamente indisponível.",provisioning_failed:"Não foi possível preparar sua agenda. Tente novamente."}[result.error?.code])||"Não foi possível concluir agora.");return result.data}
  form.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity())return;submit.disabled=true;message.textContent="Preparando seu ambiente...";const data=Object.fromEntries(new FormData(form));try{const result=await call({action:"start_trial",business_name:data.business_name,responsible_name:data.responsible_name,tax_document:data.tax_document,email:data.email,phone:data.phone,segment:data.segment,cycle:data.cycle,payment_method:data.payment_method,terms_version:TERMS_VERSION,accepted_terms:Boolean(data.accepted_terms),accepted_privacy:true,recurring_authorized:Boolean(data.recurring_authorized),website:data.website||""});location.hash=`manage=${encodeURIComponent(result.management_token)}`;document.querySelector("#signupSection").hidden=true;document.querySelector("#resultSection").hidden=false;document.querySelector("#resultMessage").textContent=`Seu acesso gratuito está liberado até ${new Date(result.trial_ends_at).toLocaleString("pt-BR")}. Enviamos o convite de acesso para ${data.email}.`;if(result.checkout_url){const link=document.querySelector("#checkoutLink");link.hidden=false;link.href=result.checkout_url}else document.querySelector("#manageMessage").textContent="O Pix será gerado e enviado automaticamente 48 horas antes do fim do teste; não há cobrança antecipada."}catch(error){message.textContent=error.message;submit.disabled=false}});
  async function restoreManagement(){const token=new URLSearchParams(location.hash.slice(1)).get("manage");if(!token)return;document.querySelector("#signupSection").hidden=true;document.querySelector("#resultSection").hidden=false;document.querySelector("#resultMessage").textContent="Carregando sua contratação...";try{const result=await call({action:"status"},token);document.querySelector("#resultMessage").textContent=`${result.business_name}: situação ${result.status}. Acesso previsto até ${new Date(result.access_until||result.trial_ends_at).toLocaleString("pt-BR")}.`;document.querySelector("#cancelButton").disabled=["cancelled","cancel_at_period_end"].includes(result.status)}catch(error){document.querySelector("#manageMessage").textContent=error.message}}
  document.querySelector("#copyPix").addEventListener("click",()=>navigator.clipboard.writeText(document.querySelector("#pixCode").value)); document.querySelector("#cancelButton").addEventListener("click",async()=>{const token=new URLSearchParams(location.hash.slice(1)).get("manage");if(!token)return;const reason=prompt("Se quiser, informe o motivo do cancelamento:")||"";try{const result=await call({action:"cancel",reason},token);document.querySelector("#manageMessage").textContent=`Renovação cancelada. Seu acesso permanece disponível até ${new Date(result.access_until).toLocaleString("pt-BR")}.`;document.querySelector("#cancelButton").disabled=true}catch(error){document.querySelector("#manageMessage").textContent=error.message}});restoreManagement();
})();
